services:
  poller:
    image: poller
    build:
      context: runner
      dockerfile: poller/Dockerfile
    mem_limit: 256m
    volumes:
      - ./cache:/code/data
      - ./config:/code/config
      - ./src:/src
  executor:
    depends_on:
      - poller
    image: executor
    build:
      context: runner
      dockerfile: executor/Dockerfile
    volumes:
      - ./cache:/code/data
    environment:
      - APP_MODULE_PATH=data.src
      - WORKER_COUNT=1
    ports:
      - 8080:8080
    env_file:
      - runner/executor/.env
