version: "3"

services:
  poller:
    build:
      context: runner
      dockerfile: poller/Dockerfile
    mem_limit: 256m
    cpus: '0.5'
    volumes:
      - ./cache:/code/data
      - ./config:/code/config
      - ./src:/src
  executor:
    depends_on:
      - poller
    build:
      context: runner
      dockerfile: executor/Dockerfile
    volumes:
      - ./cache:/code/data
    environment:
      - APP_MODULE_PATH=data.src.app
      - WORKER_COUNT=1
    ports:
      - 8080:8080
    env_file:
      - runner/executor/.env
