name: Write References in docs/SUMMARY.md

on:
  push:
    branches:
      - main
    paths:
      - 'docs/reference/common/**'
      - 'docs/reference/dsl/**'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script
      run: python docs/scripts/set-reference.py


    - name: Commit and push if there are changes
      env:
        GIT_AUTHOR_NAME: Arunesh Singh
        GIT_AUTHOR_EMAIL: 43724007+AruneshSingh@users.noreply.github.com
        GIT_COMMITTER_NAME: Arunesh Singh
        GIT_COMMITTER_EMAIL: 43724007+AruneshSingh@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
      run: |
        git add .
        git commit -m "docs: update summary.md" || exit 0  # Exit 0 if no changes
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DATA_PUSH_TOKEN }}
